invMan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
  path(
    '',
    views.product_list,
    name='product_list'
  ),
  path(
    '<slug:category_slug>/',
    views.product_list,
    name='product_list_by_category'
  ), 
  path(
    '<int:id>/<slug:slug>/',
    views.product_detail,
    name='product_detail'
  ),

]

shop/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse

class Category(models.Model):
  name = models.CharField(max_length=128, db_index=True)
  slug = models.SlugField(max_length=128, unique=True)
  
  class Meta:
    ordering = ('name',)
    verbose_name = 'category'
    verbose_name_plural = 'categories'

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse(
      'shop:product_list_by_category', 
      args=[self.slug]
    )

class Supplier(models.Model):
  name = models.CharField(max_length=128, db_index=True)
  slug = models.SlugField(max_length=128, unique=True)
  
  class Meta:
    ordering = ('name',)
    verbose_name = 'supplier'
    verbose_name_plural = 'suppliers'

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse(
      'shop:product_list_by_supplier', 
      args=[self.slug]
    )

class Brand(models.Model):
  name = models.CharField(max_length=128, db_index=True)
  slug = models.SlugField(max_length=128, unique=True)
  
  class Meta:
    ordering = ('name',)
    verbose_name = 'brand'
    verbose_name_plural = 'brands'

  def __str__(self):
    return self.name

class Product(models.Model):

  # barcode = models.AutoField(
  #   verbose_name='ID', 
  #   serialize=False, 
  #   auto_created=True, 
  #   primary_key=True
  # )
  category = models.ForeignKey(
    Category,
    related_name='products',
    on_delete=models.CASCADE
  )
  supplier = models.ForeignKey(
    Supplier,
    related_name='products',
    on_delete=models.CASCADE
  )
  brand = models.ForeignKey(
    Brand,
    related_name='products',
    on_delete=models.CASCADE
  )
  # barcode = models.TextField(
  #   max_length=48,
  #   default=str(100+id)
  # )
  @property
  def bqcode(self):
    return (100 + self.id)
  
  made = models.TextField(
    max_length=10, 
    default=datetime.now().year
  )
  name = models.CharField(max_length=128, db_index=True)
  slug = models.SlugField(max_length=128, db_index=True)

  image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
  description = models.TextField(blank=True)
  price = models.DecimalField(max_digits=20, decimal_places=0)

  available = models.BooleanField(default=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  class Meta:
    ordering = ('name',) 
    index_together = (('id', 'slug'),)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse(
      'shop:product_detail',
      args=[self.id, self.slug]
    )

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from .bqcode import SaveBQCodetoFnm
import sys, os

def product_list(request, category_slug=None):
  category = None
  categories = Category.objects.all()
  products = Product.objects.filter(available=True)
  if category_slug:
    category = get_object_or_404(Category, slug=category_slug)
    products = products.filter(category=category)
  return render(
    request,
    'shop/product/list.html',
    {'category': category,
    'categories': categories,
    'products': products}
  )

def product_detail(request, id, slug):
  product = get_object_or_404(
    Product,
    id=id, slug=slug,
    available=True
  ) 

  SaveBQCodetoFnm(
    'code39', 
    str(product.bqcode), 
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + \
    '/shop/static/img/bqcode/' + \
    str(product.bqcode) + '.png'
  )

  return render(
    request,
    'shop/product/detail.html',
    {'product': product}
  )

shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "asset/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "img/InvLogo.png" %}">

  <title>Accessories</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="{% static "img/InvLogo.png" %}" width="40" height="40" class="d-inline-block align-top" alt="Accessories barcode/qrcode">
        <span>Accessories barcode/qrcode</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static " asset/Dưới Mái Học Đường.pdf" %}">eBook</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.facebook.com/pvh.free" target="_blank">Faebook</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/freeblogger" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="/admin/shop" class="btn btn-primary">Admin</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

shop/templates/shop/base1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8" />

  <title>{% block title %}My shop{% endblock %}</title>

  <link rel="icon" type="image/png" href="{% static "img/InvLogo.png" %}">
  
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">

</head>

<body>

  <div id="header">

    <a href="/" class="logo"><h1><img src="{% static "img/InvLogo.png" %}" width="40"> Accessories barcode/qrcode</h1></a>

  </div>

  <div id="subheader">

    <div class="cart">

      <h2>Inventory Management</h2>

    </div>
  </div>

  <div id="content">

    {% block content %} {% endblock %} </div>
</body>

</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %} 

{% load static %}

{% block title %} {{ product.name }} {% endblock %}

{% block content %}

<div class="product-detail">
  <img src="{% if product.image %}{{ product.image.url }}{% else %} {% static 'img/no_image.png' %}{% endif %}">
  <h1>{{ product.name }}</h1>
    <h2> 
      <a href="{{ product.category.get_absolute_url }}"> 
        {{ product.category }}
      </a>
    </h2> 
    <h3>
      <p class="price">{{ product.price }} VNĐ</p> 
    </h3>
    <img src="{% static 'img/bqcode/' %}{{ product.bqcode }}.png">
  {{ product.description|linebreaks }} 
</div> {% endblock %}

shop/templates/shop/product/home.html
{% extends "../base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'asset/LogicLogo.png' %}" class="img-fluid", width="160">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">🌏 SeaSun Enter Tech 🛩</h1>
  </div>
</div>

<h2 class="mt-5">Projects</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %} 

{% load static %}

{% block title %} 
  {% if category %}{{ category.name }}{% else %}Products{% endif %} 
{% endblock %}

{% block content %}

<div id="sidebar">

<h3>Categories</h3> 
<ul> 
  <li {% if not category %}class="selected"{% endif %}>
    <a href="{% url 'shop:product_list' %}">All</a>
  </li> 
  {% for c in categories %} 
    <li {% if category.slug == c.slug %}class="selected" {% endif %}> 
      <a href="{{ c.get_absolute_url }}">{{ c.name }}</a> 
    </li> 
  {% endfor %} 
</ul> 

</div>

<div id="main" class="product-list">

<h1>
  {% if category %}{{ category.name }}{% else %}Products {% endif %}
</h1> 

{% for product in products %}
  <div class="item">

    <a href="{{ product.get_absolute_url }}"> 
      <img src="{% if product.image %}
        {{ product.image.url }}
        {% else %}{% static 'img/no_image.png' %}
        {% endif %}" width="128"> 
    </a> 
    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
    <br> {{ product.price }} VNĐ

    <!-- {% for s in suppliers %}
    <li
      {% if supplier.slug == s.slug  %}class="selected" {% endif %}> 
      <a href="{{ s.get_absolute_url }}">{{ s.name }}</a> 
    </li>
    {% endfor %} -->

  </div>
{% endfor %}
</div> 
{% endblock %}